FORMAT: 1A
HOST: http://secrets.agilestacks.com/api/v1

# Secrets Service API

Secrets Service has protected HTTP API to provide access to all it's functions, such as:

- saving and retrieving secrets.
