apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{DEPLOYMENT_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    provider: agilestacks.com
    project: secrets-service
    qualifier: api
spec:
  replicas: 1
  template:
    metadata:
      name: {{DEPLOYMENT_NAME}}
      namespace: {{NAMESPACE}}
      labels:
        provider: agilestacks.com
        project: secrets-service
        qualifier: api
    spec:
      containers:
      - name: api
        image: {{IMAGE_NAME}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 3001
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 3001
          initialDelaySeconds: 60
          timeoutSeconds: 3
